### ISSUE TITLE
Swerve Drive Wiring

### ISSUE THREAD

**Issue by drewwhis** [frc538/2020-infinite-recharge#11]
- [x] Neos on drive need the Anderson connectors
- [x] Sparks for drive need the Anderson connectors
- [x] Sparks need to be placed close to the Neos (for the encoder wire)
- [x] Sparks need to be wired to the PDP using 12 AWG to the 40A ports
- [x] Absolute encoders need to be wired to the analog ports of the roboRIO
- [x] Sparks need to be on a CAN Bus (daisy-chain)
- [x] Sparks need to be configured (40A, Brushless) (go @mwn319 !)

~~We may need to get some longer wires for the absolute encoders.~~
- [x] Cable management (don't make a rat nest)

**Comment by drewwhis** [comment]
I think I had originally said that the Sparks would need to be close to each other. That is still ideal, but it is most important that the Sparks be close to their Neos (so the encoder wire is long enough).

The biggest challenge, I think, will be getting the absolute encoders (one per module) to the roboRIO.

**Comment by drewwhis** [comment]
re: the absolute encoder wiring.

The three wires are 26 AWG. We can break the wire and splice in additional wire to make them long enough for what we need. Shouldn't be terribly difficult - just possibly time consuming.

We should use the PWM wires that are in the rub with the encoder wires. They already have the end that goes to the roboRIO on them; we just have to look up which PWM wire goes to which encoder wire. (https://www.andymark.com/products/3-pin-encoder-cable)

**Comment by drewwhis** [comment]
When everything is hooked up, we should test by commenting out the line in SwerveModule that sets the drive motor.

Then we should turn on the drive motor but turn off the turn motor.

Then we can test with both.

**Comment by drewwhis** [comment]
@HeathHudson We got the Sparks mounted to some polycarb plates to be placed on the robot. The PDP and the main breaker were added to another sheet.

@mwn319 should be able to get you up to speed (Charlie, too).

**Comment by drewwhis** [comment]
@mwn319 where are we at on this?

**Comment by whymaison** [comment]
I had to take the sparks off of the sheet they were on and cut the sheets because they were too big. We started mounting them on the undercarriage.

**Comment by drewwhis** [comment]
@mwn319 @HeathHudson if you get to the CAN wiring tonight, the parts that plug into the SparkMax are in a SparkMax box on the table or in the red tote.

There's also a SparkMax box (either on the table or in the red tote) that has clips to make sure the CAN wires stay connected.

It would be nice if we didn't have to cut the terminals off any CAN wires, but I don't know if we have the materials to make our own clips.

**Comment by drewwhis** [comment]
@mwn319 @HeathHudson this is done for testing. I'll add a task to cleanup/maintain the wiring for the final product.
